# Generated by tests.differential.grammar from seed 11094 (typed); refactored by towel (types on), its behaviour changed.
# Rerun: python -m tests.differential.fuzz --count 1 --seed 11094 --typed
# The audit's gram_t11094.
# Round-3 audit P1-2: the block starts or ends inside a ';' line, which is spliced whole; mypy strict accepts the deletion.
if __name__ == "__main__":
    import pkg.m as M
    import copy
    import re

    def _shown(value):
        return re.sub(r"0x[0-9a-fA-F]+", "0xADDR", repr(value))

    def _calls(label, function, argument_sets):
        for arguments in argument_sets:
            arguments = copy.deepcopy(arguments)
            try:
                outcome = "-> " + _shown(function(*arguments))
            except Exception as error:
                outcome = f"raised {type(error).__name__}: {_shown(str(error))}"
            print(label, outcome, "| arguments after:", _shown(arguments))

    def _value(label, produce):
        try:
            print(label, "=", _shown(produce()))
        except Exception as error:
            print(label, "raised", type(error).__name__, _shown(str(error)))

    _calls('M.K().f1', M.K().f1, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K().f2', M.K().f2, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K().f3', M.K().f3, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _value('M.LOG[-50:]', lambda: M.LOG[-50:])
    _value('M.G', lambda: M.G)
    _value('public names of M', lambda: sorted(name for name in dir(M) if not name.startswith('_')))
