# Copyright 2025-2026 Eric Allen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The standard library that some platform or some supported Python lacks, as its documentation says.

A helper's host is imported wherever its borrower is, so a host that imports
``msvcrt``, or reads ``os.startfile`` or ``signal.CTRL_C_EVENT``, breaks a
borrower on macOS and Linux that imported fine before. ``sys.stdlib_module_names``
cannot tell: it lists every module of every platform, and only those of the
Python Towel runs on.

``PLATFORM_ONLY`` is read from the Availability notes of the documentation
sources (``Doc/library/*.rst``) of CPython 3.11.15, 3.12.13 and 3.13.7: a
module's ``:platform:`` option and a note of its own, and the note in the
description of each function, class, exception and data item at a module's
top level. An entry lists, for each version whose documentation notes it, the
desktop platforms of Windows, macOS and Linux the note names, and it is here
only where that leaves one out. ``Unix`` and ``POSIX`` name macOS and Linux
(the documentation says a Unix note holds for macOS unless it says
otherwise), and a minimum release (``Linux >= 3.9``) counts as the platform.

Left out, and so never known to be missing:

- what a note restricts only to WebAssembly and mobile platforms
  (``not WASI``, ``not Android, not iOS``). The documentation says those
  notes mean a module "does not work or is not available", and that
  ``subprocess`` and ``socket`` import there;
- an object whose description holds several notes, one per parameter:
  ``subprocess.Popen``, ``os.pidfd_open``;
- a note the running interpreters contradict, which the documentation
  places on Linux or iOS alone and CPython 3.11 to 3.13 has on macOS too:
  ``os.preadv``, ``os.pwritev``, the ``sys`` stack-trampoline functions and
  ``importlib.machinery.AppleFrameworkLoader``;
- availability stated in prose rather than a note, such as the ``os.O_*``
  constants' "only available on Windows", and undocumented private modules
  (``_winapi``, ``nt``).

``NEEDS_TK`` holds ``tkinter``, which its documentation says is available on
"most Unix platforms, including macOS, as well as on Windows", with the
submodules it marks ``:platform: Tk``. ``STDLIB_ON_EVERY_VERSION`` holds the
names ``sys.stdlib_module_names`` gives on every supported version, so a
module one version removed (``distutils``, ``imp``, ``cgi``) or added is
not taken to be there on another.

tests/test_known_platforms.py holds the running interpreter to every entry
that names its platform as lacking it and to the version lists, so a Python
that adds one fails the suite and returns the list for review.
"""

from __future__ import annotations

from dataclasses import dataclass
from fnmatch import fnmatchcase
from typing import Dict, FrozenSet, Mapping, Tuple

DESKTOP_PLATFORMS: FrozenSet[str] = frozenset({"Windows", "macOS", "Linux"})

_LETTERS = {"W": "Windows", "M": "macOS", "L": "Linux"}


@dataclass(frozen=True)
class PlatformOnly:
    """A module, or a module's attribute, that the documentation places on some desktop platforms only."""

    name: str
    """Its dotted name: ``msvcrt``, ``os.startfile``, or a pattern of names such as ``socket.CAN_*``."""
    is_module: bool
    present_on: Mapping[str, FrozenSet[str]]
    """For each version (``"3.11"``) whose documentation notes it, the desktop platforms it names."""
    source: str
    """The documentation file whose note it is, below ``Doc/library``."""


def _entries(
    source: str, present_on: Mapping[str, str], *names: str, is_module: bool
) -> Tuple[PlatformOnly, ...]:
    platforms = {
        version: frozenset(_LETTERS[letter] for letter in letters if letter in _LETTERS)
        for version, letters in present_on.items()
    }
    return tuple(PlatformOnly(name, is_module, platforms, source) for name in names)


def _modules(source: str, present_on: Mapping[str, str], *names: str) -> Tuple[PlatformOnly, ...]:
    return _entries(source, present_on, *names, is_module=True)


def _attributes(
    source: str, present_on: Mapping[str, str], *names: str
) -> Tuple[PlatformOnly, ...]:
    return _entries(source, present_on, *names, is_module=False)


PLATFORM_ONLY: Tuple[PlatformOnly, ...] = (
    *_modules(
        "codecs.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "encodings.mbcs",
    ),
    *_modules(
        "crypt.rst",
        {"3.11": "LM", "3.12": "LM"},
        "crypt",
    ),
    *_modules(
        "curses.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "curses",
    ),
    *_modules(
        "dbm.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "dbm.gnu",
        "dbm.ndbm",
    ),
    *_modules(
        "fcntl.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "fcntl",
    ),
    *_modules(
        "grp.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "grp",
    ),
    *_modules(
        "msilib.rst",
        {"3.11": "W", "3.12": "W"},
        "msilib",
    ),
    *_modules(
        "msvcrt.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "msvcrt",
    ),
    *_modules(
        "nis.rst",
        {"3.11": "LM", "3.12": "LM"},
        "nis",
    ),
    *_modules(
        "ossaudiodev.rst",
        {"3.11": "L", "3.12": "L"},
        "ossaudiodev",
    ),
    *_modules(
        "pipes.rst",
        {"3.11": "LM", "3.12": "LM"},
        "pipes",
    ),
    *_modules(
        "posix.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "posix",
    ),
    *_modules(
        "pty.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "pty",
    ),
    *_modules(
        "pwd.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "pwd",
    ),
    *_modules(
        "readline.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "readline",
    ),
    *_modules(
        "resource.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "resource",
    ),
    *_modules(
        "spwd.rst",
        {"3.11": "LM", "3.12": "LM"},
        "spwd",
    ),
    *_modules(
        "syslog.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "syslog",
    ),
    *_modules(
        "termios.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "termios",
    ),
    *_modules(
        "tty.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "tty",
    ),
    *_modules(
        "winreg.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "winreg",
    ),
    *_modules(
        "winsound.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "winsound",
    ),
    *_attributes(
        "asyncio-eventloop.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "asyncio.ProactorEventLoop",
    ),
    *_attributes(
        "asyncio-policy.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "asyncio.WindowsProactorEventLoopPolicy",
        "asyncio.WindowsSelectorEventLoopPolicy",
    ),
    *_attributes(
        "asyncio-stream.rst",
        {"3.12": "LM", "3.13": "LM"},
        "asyncio.open_unix_connection",
        "asyncio.start_unix_server",
    ),
    *_attributes(
        "asyncore.rst",
        {"3.11": "LM"},
        "asyncore.file_dispatcher",
        "asyncore.file_wrapper",
    ),
    *_attributes(
        "ctypes.rst",
        {"3.12": "W", "3.13": "W"},
        "ctypes.DllCanUnloadNow",
        "ctypes.DllGetClassObject",
        "ctypes.FormatError",
        "ctypes.GetLastError",
        "ctypes.HRESULT",
        "ctypes.OleDLL",
        "ctypes.WINFUNCTYPE",
        "ctypes.WinDLL",
        "ctypes.WinError",
        "ctypes.find_msvcrt",
        "ctypes.get_last_error",
        "ctypes.oledll",
        "ctypes.set_last_error",
        "ctypes.windll",
    ),
    *_attributes(
        "errno.rst",
        {"3.11": "-", "3.12": "-", "3.13": "-"},
        "errno.ENOTCAPABLE",
    ),
    *_attributes(
        "os.rst",
        {"3.11": "L", "3.12": "L", "3.13": "L"},
        "os.EFD_CLOEXEC",
        "os.EFD_NONBLOCK",
        "os.EFD_SEMAPHORE",
        "os.MFD_ALLOW_SEALING",
        "os.MFD_CLOEXEC",
        "os.MFD_HUGETLB",
        "os.MFD_HUGE_16GB",
        "os.MFD_HUGE_16MB",
        "os.MFD_HUGE_1GB",
        "os.MFD_HUGE_1MB",
        "os.MFD_HUGE_256MB",
        "os.MFD_HUGE_2GB",
        "os.MFD_HUGE_2MB",
        "os.MFD_HUGE_32MB",
        "os.MFD_HUGE_512KB",
        "os.MFD_HUGE_512MB",
        "os.MFD_HUGE_64KB",
        "os.MFD_HUGE_8MB",
        "os.MFD_HUGE_MASK",
        "os.MFD_HUGE_SHIFT",
        "os.RWF_APPEND",
        "os.RWF_DSYNC",
        "os.RWF_HIPRI",
        "os.RWF_NOWAIT",
        "os.RWF_SYNC",
        "os.copy_file_range",
        "os.eventfd",
        "os.eventfd_read",
        "os.eventfd_write",
        "os.getrandom",
        "os.memfd_create",
        "os.splice",
    ),
    *_attributes(
        "os.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "os.CLD_CONTINUED",
        "os.CLD_DUMPED",
        "os.CLD_EXITED",
        "os.CLD_KILLED",
        "os.CLD_STOPPED",
        "os.CLD_TRAPPED",
        "os.EX_CANTCREAT",
        "os.EX_CONFIG",
        "os.EX_DATAERR",
        "os.EX_IOERR",
        "os.EX_NOHOST",
        "os.EX_NOINPUT",
        "os.EX_NOPERM",
        "os.EX_NOTFOUND",
        "os.EX_NOUSER",
        "os.EX_OSERR",
        "os.EX_OSFILE",
        "os.EX_PROTOCOL",
        "os.EX_SOFTWARE",
        "os.EX_TEMPFAIL",
        "os.EX_UNAVAILABLE",
        "os.EX_USAGE",
        "os.F_LOCK",
        "os.F_TEST",
        "os.F_TLOCK",
        "os.F_ULOCK",
        "os.POSIX_FADV_DONTNEED",
        "os.POSIX_FADV_NOREUSE",
        "os.POSIX_FADV_NORMAL",
        "os.POSIX_FADV_RANDOM",
        "os.POSIX_FADV_SEQUENTIAL",
        "os.POSIX_FADV_WILLNEED",
        "os.PRIO_PGRP",
        "os.PRIO_PROCESS",
        "os.PRIO_USER",
        "os.P_ALL",
        "os.P_PGID",
        "os.P_PID",
        "os.P_PIDFD",
        "os.SEEK_DATA",
        "os.SEEK_HOLE",
        "os.SF_MNOWAIT",
        "os.SF_NOCACHE",
        "os.SF_NODISKIO",
        "os.SF_SYNC",
        "os.WCONTINUED",
        "os.WCOREDUMP",
        "os.WEXITED",
        "os.WEXITSTATUS",
        "os.WIFCONTINUED",
        "os.WIFEXITED",
        "os.WIFSIGNALED",
        "os.WIFSTOPPED",
        "os.WNOHANG",
        "os.WNOWAIT",
        "os.WSTOPPED",
        "os.WSTOPSIG",
        "os.WTERMSIG",
        "os.WUNTRACED",
        "os.chflags",
        "os.chown",
        "os.chroot",
        "os.confstr",
        "os.confstr_names",
        "os.ctermid",
        "os.fchdir",
        "os.fchown",
        "os.fdatasync",
        "os.fork",
        "os.forkpty",
        "os.fpathconf",
        "os.fstatvfs",
        "os.fwalk",
        "os.getegid",
        "os.getenvb",
        "os.geteuid",
        "os.getgid",
        "os.getgrouplist",
        "os.getgroups",
        "os.getloadavg",
        "os.getpgid",
        "os.getpgrp",
        "os.getpriority",
        "os.getresgid",
        "os.getresuid",
        "os.getsid",
        "os.getuid",
        "os.initgroups",
        "os.killpg",
        "os.lchflags",
        "os.lchown",
        "os.lockf",
        "os.login_tty",
        "os.mkfifo",
        "os.mknod",
        "os.nice",
        "os.openpty",
        "os.pathconf",
        "os.pathconf_names",
        "os.pipe2",
        "os.plock",
        "os.posix_fadvise",
        "os.posix_fallocate",
        "os.posix_spawn",
        "os.posix_spawnp",
        "os.pread",
        "os.pwrite",
        "os.readv",
        "os.register_at_fork",
        "os.sendfile",
        "os.setegid",
        "os.seteuid",
        "os.setgid",
        "os.setgroups",
        "os.setpgid",
        "os.setpgrp",
        "os.setpriority",
        "os.setregid",
        "os.setresgid",
        "os.setresuid",
        "os.setreuid",
        "os.setsid",
        "os.setuid",
        "os.statvfs",
        "os.sync",
        "os.sysconf",
        "os.sysconf_names",
        "os.tcgetpgrp",
        "os.tcsetpgrp",
        "os.ttyname",
        "os.uname",
        "os.wait",
        "os.wait3",
        "os.wait4",
        "os.waitid",
        "os.writev",
    ),
    *_attributes(
        "os.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LMW"},
        "os.fchmod",
        "os.lchmod",
    ),
    *_attributes(
        "os.rst",
        {"3.11": "LM", "3.12": "LMW", "3.13": "LMW"},
        "os.get_blocking",
        "os.set_blocking",
    ),
    *_attributes(
        "os.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "os.P_DETACH",
        "os.P_OVERLAY",
        "os.add_dll_directory",
        "os.get_handle_inheritable",
        "os.set_handle_inheritable",
        "os.startfile",
    ),
    *_attributes(
        "os.rst",
        {"3.12": "L", "3.13": "L"},
        "os.setns",
        "os.unshare",
    ),
    *_attributes(
        "os.rst",
        {"3.12": "M", "3.13": "M"},
        "os.PRIO_DARWIN_BG",
        "os.PRIO_DARWIN_NONUI",
        "os.PRIO_DARWIN_PROCESS",
        "os.PRIO_DARWIN_THREAD",
    ),
    *_attributes(
        "os.rst",
        {"3.12": "W", "3.13": "W"},
        "os.listdrives",
        "os.listmounts",
        "os.listvolumes",
    ),
    *_attributes(
        "os.rst",
        {"3.13": "L"},
        "os.TFD_CLOEXEC",
        "os.TFD_NONBLOCK",
        "os.TFD_TIMER_ABSTIME",
        "os.TFD_TIMER_CANCEL_ON_SET",
        "os.timerfd_create",
        "os.timerfd_gettime",
        "os.timerfd_gettime_ns",
        "os.timerfd_settime",
        "os.timerfd_settime_ns",
    ),
    *_attributes(
        "os.rst",
        {"3.13": "LM"},
        "os.grantpt",
        "os.posix_openpt",
        "os.ptsname",
        "os.unlockpt",
    ),
    *_attributes(
        "os.path.rst",
        {"3.12": "W"},
        "os.path.isdevdrive",
    ),
    *_attributes(
        "os.path.rst",
        {"3.13": "W"},
        "os.path.isreserved",
    ),
    *_attributes(
        "resource.rst",
        {"3.11": "-", "3.12": "-", "3.13": "-"},
        "resource.RLIMIT_KQUEUES",
        "resource.RLIMIT_NPTS",
        "resource.RLIMIT_SBSIZE",
        "resource.RLIMIT_SWAP",
        "resource.RLIMIT_VMEM",
    ),
    *_attributes(
        "resource.rst",
        {"3.11": "L", "3.12": "L", "3.13": "L"},
        "resource.RLIMIT_MSGQUEUE",
        "resource.RLIMIT_NICE",
        "resource.RLIMIT_RTPRIO",
        "resource.RLIMIT_RTTIME",
        "resource.RLIMIT_SIGPENDING",
        "resource.prlimit",
    ),
    *_attributes(
        "select.rst",
        {"3.12": "LM", "3.13": "LM"},
        "select.PIPE_BUF",
    ),
    *_attributes(
        "shutil.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "shutil.chown",
    ),
    *_attributes(
        "signal.rst",
        {"3.11": "L", "3.12": "L", "3.13": "L"},
        "signal.SIGSTKFLT",
        "signal.pidfd_send_signal",
    ),
    *_attributes(
        "signal.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "signal.SIGALRM",
        "signal.SIGBUS",
        "signal.SIGCHLD",
        "signal.SIGCONT",
        "signal.SIGHUP",
        "signal.SIGKILL",
        "signal.SIGPIPE",
        "signal.SIGUSR1",
        "signal.SIGUSR2",
        "signal.SIGWINCH",
        "signal.Sigmasks",
        "signal.alarm",
        "signal.getitimer",
        "signal.pause",
        "signal.pthread_kill",
        "signal.pthread_sigmask",
        "signal.setitimer",
        "signal.siginterrupt",
        "signal.sigpending",
        "signal.sigtimedwait",
        "signal.sigwait",
        "signal.sigwaitinfo",
    ),
    *_attributes(
        "signal.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "signal.CTRL_BREAK_EVENT",
        "signal.CTRL_C_EVENT",
        "signal.SIGBREAK",
    ),
    *_attributes(
        "socket.rst",
        {"3.11": "-", "3.12": "-", "3.13": "-"},
        "socket.LOCAL_CREDS",
        "socket.LOCAL_CREDS_PERSISTENT",
        "socket.SCM_CREDS2",
    ),
    *_attributes(
        "socket.rst",
        {"3.11": "L", "3.12": "L", "3.13": "L"},
        "socket.AF_ALG",
        "socket.AF_CAN",
        "socket.AF_PACKET",
        "socket.AF_QIPCRTR",
        "socket.AF_RDS",
        "socket.AF_VSOCK",
        "socket.ALG_*",
        "socket.CAN_*",
        "socket.CAN_BCM",
        "socket.CAN_BCM_*",
        "socket.CAN_ISOTP",
        "socket.CAN_J1939",
        "socket.CAN_RAW_FD_FRAMES",
        "socket.CAN_RAW_JOIN_FILTERS",
        "socket.IOCTL_VM_SOCKETS_GET_LOCAL_CID",
        "socket.PACKET_*",
        "socket.PF_CAN",
        "socket.PF_PACKET",
        "socket.PF_RDS",
        "socket.RDS_*",
        "socket.SOCK_CLOEXEC",
        "socket.SOCK_NONBLOCK",
        "socket.SOL_ALG",
        "socket.SOL_CAN_*",
        "socket.SOL_RDS",
        "socket.SO_INCOMING_CPU",
        "socket.SO_VM*",
        "socket.VMADDR*",
    ),
    *_attributes(
        "socket.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "socket.CMSG_LEN",
        "socket.CMSG_SPACE",
        "socket.sethostname",
    ),
    *_attributes(
        "socket.rst",
        {"3.11": "LMW", "3.12": "LMW", "3.13": "LM"},
        "socket.recv_fds",
        "socket.send_fds",
    ),
    *_attributes(
        "socket.rst",
        {"3.11": "M", "3.12": "M", "3.13": "M"},
        "socket.AF_LINK",
    ),
    *_attributes(
        "socket.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "socket.fromshare",
    ),
    *_attributes(
        "socket.rst",
        {"3.12": "-", "3.13": "-"},
        "socket.AF_DIVERT",
        "socket.PF_DIVERT",
    ),
    *_attributes(
        "socket.rst",
        {"3.12": "L", "3.13": "L"},
        "socket.ETH_P_ALL",
    ),
    *_attributes(
        "socket.rst",
        {"3.12": "LM", "3.13": "LM"},
        "socket.ETHERTYPE_ARP",
        "socket.ETHERTYPE_IP",
        "socket.ETHERTYPE_IPV6",
        "socket.ETHERTYPE_VLAN",
    ),
    *_attributes(
        "socket.rst",
        {"3.12": "W", "3.13": "W"},
        "socket.AF_HYPERV",
        "socket.HVSOCKET_ADDRESS_FLAG_PASSTHRU",
        "socket.HVSOCKET_CONNECTED_SUSPEND",
        "socket.HVSOCKET_CONNECT_TIMEOUT",
        "socket.HVSOCKET_CONNECT_TIMEOUT_MAX",
        "socket.HV_GUID_BROADCAST",
        "socket.HV_GUID_CHILDREN",
        "socket.HV_GUID_LOOPBACK",
        "socket.HV_GUID_PARENT",
        "socket.HV_GUID_WILDCARD",
        "socket.HV_GUID_ZERO",
        "socket.HV_PROTOCOL_RAW",
    ),
    *_attributes(
        "ssl.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "ssl.enum_certificates",
        "ssl.enum_crls",
    ),
    *_attributes(
        "stat.rst",
        {"3.13": "M"},
        "stat.SF_SUPPORTED",
        "stat.SF_SYNTHETIC",
    ),
    *_attributes(
        "sys.rst",
        {"3.11": "-", "3.12": "-", "3.13": "-"},
        "sys._emscripten_info",
        "sys.getandroidapilevel",
    ),
    *_attributes(
        "sys.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "sys.getdlopenflags",
        "sys.setdlopenflags",
    ),
    *_attributes(
        "sys.rst",
        {"3.11": "W", "3.12": "W", "3.13": "W"},
        "sys._enablelegacywindowsfsencoding",
        "sys.dllhandle",
        "sys.getwindowsversion",
        "sys.winver",
    ),
    *_attributes(
        "sys.rst",
        {"3.12": "LM", "3.13": "LM"},
        "sys.abiflags",
    ),
    *_attributes(
        "time.rst",
        {"3.11": "-", "3.12": "-", "3.13": "-"},
        "time.CLOCK_HIGHRES",
        "time.CLOCK_PROF",
        "time.CLOCK_UPTIME",
    ),
    *_attributes(
        "time.rst",
        {"3.11": "L", "3.12": "L", "3.13": "L"},
        "time.CLOCK_BOOTTIME",
        "time.CLOCK_TAI",
    ),
    *_attributes(
        "time.rst",
        {"3.11": "LM", "3.12": "LM", "3.13": "LM"},
        "time.CLOCK_MONOTONIC",
        "time.CLOCK_MONOTONIC_RAW",
        "time.CLOCK_PROCESS_CPUTIME_ID",
        "time.CLOCK_REALTIME",
        "time.CLOCK_THREAD_CPUTIME_ID",
        "time.clock_getres",
        "time.clock_gettime",
        "time.clock_gettime_ns",
        "time.clock_settime",
        "time.clock_settime_ns",
        "time.pthread_getcpuclockid",
        "time.tzset",
    ),
    *_attributes(
        "time.rst",
        {"3.11": "M", "3.12": "M", "3.13": "M"},
        "time.CLOCK_UPTIME_RAW",
    ),
    *_attributes(
        "time.rst",
        {"3.13": "M"},
        "time.CLOCK_MONOTONIC_RAW_APPROX",
        "time.CLOCK_UPTIME_RAW_APPROX",
    ),
)
"""Every module and module attribute the documentation restricts to some desktop platforms."""

NEEDS_TK: FrozenSet[str] = frozenset(
    {
        "tkinter",
        "tkinter.colorchooser",
        "tkinter.commondialog",
        "tkinter.dnd",
        "tkinter.filedialog",
        "tkinter.font",
        "tkinter.messagebox",
        "tkinter.scrolledtext",
        "tkinter.simpledialog",
    }
)
"""``tkinter`` and the modules its documentation marks ``:platform: Tk``: absent wherever Python lacks Tk."""

STDLIB_ON_EVERY_VERSION: FrozenSet[str] = frozenset(
    {
        "__future__",
        "_abc",
        "_aix_support",
        "_ast",
        "_asyncio",
        "_bisect",
        "_blake2",
        "_bz2",
        "_codecs",
        "_codecs_cn",
        "_codecs_hk",
        "_codecs_iso2022",
        "_codecs_jp",
        "_codecs_kr",
        "_codecs_tw",
        "_collections",
        "_collections_abc",
        "_compat_pickle",
        "_compression",
        "_contextvars",
        "_csv",
        "_ctypes",
        "_curses",
        "_curses_panel",
        "_datetime",
        "_dbm",
        "_decimal",
        "_elementtree",
        "_frozen_importlib",
        "_frozen_importlib_external",
        "_functools",
        "_gdbm",
        "_hashlib",
        "_heapq",
        "_imp",
        "_io",
        "_json",
        "_locale",
        "_lsprof",
        "_lzma",
        "_markupbase",
        "_md5",
        "_multibytecodec",
        "_multiprocessing",
        "_opcode",
        "_operator",
        "_osx_support",
        "_overlapped",
        "_pickle",
        "_posixshmem",
        "_posixsubprocess",
        "_py_abc",
        "_pydecimal",
        "_pyio",
        "_queue",
        "_random",
        "_scproxy",
        "_sha1",
        "_sha3",
        "_signal",
        "_sitebuiltins",
        "_socket",
        "_sqlite3",
        "_sre",
        "_ssl",
        "_stat",
        "_statistics",
        "_string",
        "_strptime",
        "_struct",
        "_symtable",
        "_thread",
        "_threading_local",
        "_tkinter",
        "_tokenize",
        "_tracemalloc",
        "_typing",
        "_uuid",
        "_warnings",
        "_weakref",
        "_weakrefset",
        "_winapi",
        "_zoneinfo",
        "abc",
        "antigravity",
        "argparse",
        "array",
        "ast",
        "asyncio",
        "atexit",
        "base64",
        "bdb",
        "binascii",
        "bisect",
        "builtins",
        "bz2",
        "cProfile",
        "calendar",
        "cmath",
        "cmd",
        "code",
        "codecs",
        "codeop",
        "collections",
        "colorsys",
        "compileall",
        "concurrent",
        "configparser",
        "contextlib",
        "contextvars",
        "copy",
        "copyreg",
        "csv",
        "ctypes",
        "curses",
        "dataclasses",
        "datetime",
        "dbm",
        "decimal",
        "difflib",
        "dis",
        "doctest",
        "email",
        "encodings",
        "ensurepip",
        "enum",
        "errno",
        "faulthandler",
        "fcntl",
        "filecmp",
        "fileinput",
        "fnmatch",
        "fractions",
        "ftplib",
        "functools",
        "gc",
        "genericpath",
        "getopt",
        "getpass",
        "gettext",
        "glob",
        "graphlib",
        "grp",
        "gzip",
        "hashlib",
        "heapq",
        "hmac",
        "html",
        "http",
        "idlelib",
        "imaplib",
        "importlib",
        "inspect",
        "io",
        "ipaddress",
        "itertools",
        "json",
        "keyword",
        "linecache",
        "locale",
        "logging",
        "lzma",
        "mailbox",
        "marshal",
        "math",
        "mimetypes",
        "mmap",
        "modulefinder",
        "msvcrt",
        "multiprocessing",
        "netrc",
        "nt",
        "ntpath",
        "nturl2path",
        "numbers",
        "opcode",
        "operator",
        "optparse",
        "os",
        "pathlib",
        "pdb",
        "pickle",
        "pickletools",
        "pkgutil",
        "platform",
        "plistlib",
        "poplib",
        "posix",
        "posixpath",
        "pprint",
        "profile",
        "pstats",
        "pty",
        "pwd",
        "py_compile",
        "pyclbr",
        "pydoc",
        "pydoc_data",
        "pyexpat",
        "queue",
        "quopri",
        "random",
        "re",
        "readline",
        "reprlib",
        "resource",
        "rlcompleter",
        "runpy",
        "sched",
        "secrets",
        "select",
        "selectors",
        "shelve",
        "shlex",
        "shutil",
        "signal",
        "site",
        "smtplib",
        "socket",
        "socketserver",
        "sqlite3",
        "sre_compile",
        "sre_constants",
        "sre_parse",
        "ssl",
        "stat",
        "statistics",
        "string",
        "stringprep",
        "struct",
        "subprocess",
        "symtable",
        "sys",
        "sysconfig",
        "syslog",
        "tabnanny",
        "tarfile",
        "tempfile",
        "termios",
        "textwrap",
        "this",
        "threading",
        "time",
        "timeit",
        "tkinter",
        "token",
        "tokenize",
        "tomllib",
        "trace",
        "traceback",
        "tracemalloc",
        "tty",
        "turtle",
        "turtledemo",
        "types",
        "typing",
        "unicodedata",
        "unittest",
        "urllib",
        "uuid",
        "venv",
        "warnings",
        "wave",
        "weakref",
        "webbrowser",
        "winreg",
        "winsound",
        "wsgiref",
        "xml",
        "xmlrpc",
        "zipapp",
        "zipfile",
        "zipimport",
        "zlib",
        "zoneinfo",
    }
)
"""The top-level names in ``sys.stdlib_module_names`` of CPython 3.11.15, 3.12.13 and 3.13.7 alike."""

STDLIB_ON_SOME_VERSIONS: Mapping[str, FrozenSet[str]] = {
    "3.11": frozenset(
        {
            "_bootsubprocess",
            "_crypt",
            "_msi",
            "_sha256",
            "_sha512",
            "aifc",
            "asynchat",
            "asyncore",
            "audioop",
            "cgi",
            "cgitb",
            "chunk",
            "crypt",
            "distutils",
            "imghdr",
            "imp",
            "lib2to3",
            "mailcap",
            "msilib",
            "nis",
            "nntplib",
            "ossaudiodev",
            "pipes",
            "smtpd",
            "sndhdr",
            "spwd",
            "sunau",
            "telnetlib",
            "uu",
            "xdrlib",
        }
    ),
    "3.12": frozenset(
        {
            "_crypt",
            "_msi",
            "_pydatetime",
            "_pylong",
            "_sha2",
            "_wmi",
            "aifc",
            "audioop",
            "cgi",
            "cgitb",
            "chunk",
            "crypt",
            "imghdr",
            "lib2to3",
            "mailcap",
            "msilib",
            "nis",
            "nntplib",
            "ossaudiodev",
            "pipes",
            "sndhdr",
            "spwd",
            "sunau",
            "telnetlib",
            "uu",
            "xdrlib",
        }
    ),
    "3.13": frozenset(
        {
            "_android_support",
            "_apple_support",
            "_colorize",
            "_interpchannels",
            "_interpqueues",
            "_interpreters",
            "_ios_support",
            "_opcode_metadata",
            "_pydatetime",
            "_pylong",
            "_pyrepl",
            "_sha2",
            "_suggestions",
            "_sysconfig",
            "_wmi",
        }
    ),
}
"""For each version, the rest of its ``sys.stdlib_module_names``: removed or added since, or private."""

_MODULES: FrozenSet[str] = frozenset(entry.name for entry in PLATFORM_ONLY if entry.is_module)
_ATTRIBUTES: Dict[str, Tuple[str, ...]] = {}
for _entry in PLATFORM_ONLY:
    if not _entry.is_module:
        _module, _, _attribute = _entry.name.rpartition(".")
        _ATTRIBUTES[_module] = (*_ATTRIBUTES.get(_module, ()), _attribute)


def platform_only(dotted: str) -> bool:
    """Whether some desktop platform's Python lacks the module or attribute ``dotted``, or its package.

    Importing ``curses.ascii`` runs ``curses``, which Windows lacks, so a
    platform-only module makes every name below it platform-only too.
    """
    parts = dotted.split(".")
    for end in range(1, len(parts) + 1):
        prefix = ".".join(parts[:end])
        if prefix in _MODULES or prefix in NEEDS_TK:
            return True
    module, _, attribute = dotted.rpartition(".")
    return any(fnmatchcase(attribute, pattern) for pattern in _ATTRIBUTES.get(module, ()))


def stdlib_everywhere(top_level: str) -> bool:
    """Whether every supported Python on every desktop platform has the top-level module ``top_level``."""
    return top_level in STDLIB_ON_EVERY_VERSION and not platform_only(top_level)
