# Copyright 2025-2026 Eric Allen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tests.differential.grammar from seed 417; refactored by towel --no-types, its behaviour changed.
# Rerun: python -m tests.differential.fuzz --count 1 --seed 417 --modes default
# The audit's gram_u0417.
# Round-3 audit P1-8: a later augmented assignment is the only read of a name the block binds, and the helper does not return it.
LOG = []
G = 5


def tr(tag, v):
    print("tr", tag, repr(v))
    LOG.append(tag)
    return v


class Box:
    def __init__(self, v):
        self.v = v

    def __repr__(self):
        return f"Box({self.v!r})"

    def __eq__(self, other):
        return isinstance(other, Box) and self.v == other.v


class Ctx:
    def __init__(self, tag):
        self.tag = tag

    def __enter__(self):
        print("enter", self.tag)
        return self.tag

    def __exit__(self, et, ev, tb):
        print("exit", self.tag, et.__name__ if et else None)
        return False


def bump():
    global G
    G += 1
    return G


class K:
    def __init__(self):
        self.count = 0

    @staticmethod
    def f1(a, b, c, o):
        v1 = (G + sum(q for q in b if q > 1))
        o.v = G
        v2 = [q * v1 for q in b if q > c['k']]
        print("comp", v2)
        with Ctx("w0") as v3:
            v4 = G; v1 *= (c['k'] // (len(f"{G}-{a}") % 5))
        print("after", v2)
        return a

    @staticmethod
    def f2(x, y, z, w):
        v1_1 = (G + sum(q for q in y if q > 1))
        w.v = (tr('q9', v1_1) // ((sum(y) - z.get('k', 0)) % 5))
        v2_1 = [q * v1_1 for q in y if q > z['k']]
        print("comp", v2_1)
        with Ctx("w0") as v3_1:
            v4_1 = G; v1_1 *= (z['k'] or y[G % 4])
        print("after", v2_1)
        return x

    @staticmethod
    def f3(a, b, c, o):
        v1_2 = (G + sum(q for q in b if q > 1))
        o.v = (tr('q9', v1_2) // ((sum(b) - c.get('k', 0)) % 5))
        v2_2 = [q * v1_2 for q in b if q > c['k']]
        print("comp", v2_2)
        with Ctx("w0") as v3_2:
            v4_2 = G; v1_2 *= (c['k'] or b[G % 4])
        print("after", v2_2)
        return a


if __name__ == "__main__":
    import sys

    import copy
    import re

    def _shown(value):
        return re.sub(r"0x[0-9a-fA-F]+", "0xADDR", repr(value))

    def _calls(label, function, argument_sets):
        for arguments in argument_sets:
            arguments = copy.deepcopy(arguments)
            try:
                outcome = "-> " + _shown(function(*arguments))
            except Exception as error:
                outcome = f"raised {type(error).__name__}: {_shown(str(error))}"
            print(label, outcome, "| arguments after:", _shown(arguments))

    def _value(label, produce):
        try:
            print(label, "=", _shown(produce()))
        except Exception as error:
            print(label, "raised", type(error).__name__, _shown(str(error)))

    M = sys.modules[__name__]
    _calls('M.K.f1', M.K.f1, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K.f2', M.K.f2, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K.f3', M.K.f3, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _value('M.LOG[-50:]', lambda: M.LOG[-50:])
    _value('M.G', lambda: M.G)
    _value('public names of M', lambda: sorted(name for name in dir(M) if not name.startswith('_')))
