# Copyright 2025-2026 Eric Allen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tests.differential.grammar from seed 898; refactored by towel --no-types, its behaviour changed.
# Rerun: python -m tests.differential.fuzz --count 1 --seed 898 --modes default
# The audit's gram_u0898.
# Round-3 audit P1-1: a for target rebinding a name bound before the block; an empty loop leaves the helper's name unbound.
LOG = []
G = 5


def tr(tag, v):
    print("tr", tag, repr(v))
    LOG.append(tag)
    return v


class Box:
    def __init__(self, v):
        self.v = v

    def __repr__(self):
        return f"Box({self.v!r})"

    def __eq__(self, other):
        return isinstance(other, Box) and self.v == other.v


class Ctx:
    def __init__(self, tag):
        self.tag = tag

    def __enter__(self):
        print("enter", self.tag)
        return self.tag

    def __exit__(self, et, ev, tb):
        print("exit", self.tag, et.__name__ if et else None)
        return False


def bump():
    global G
    G += 1
    return G


class K:
    def __init__(self):
        self.count = 0

    def f1(self, a, b, c, o):
        v1 = ((lambda q=G: q + 1)() * o.v)
        v2 = (v3 := (lambda q: q * 2 + 1)(abs(v1))) + 1
        for v2 in b:
            print("it", v2)
        print("last", v2)
        print("after", v1)
        return max(tr('y2', v2), c['k'])

    def f2(self, a, b, c, o):
        v1 = G
        v2 = (v3 := len(b)) + 1
        for v2 in b:
            print("it", v2)
        print("last", v2)
        print("after", v1)
        return max(tr('y2', v2), c['k'])

    def f3(self, a, b, c, o):
        v1 = G
        v2 = (v3 := len(b)) + 1
        for v2 in b:
            print("it", v2)
        print("last", v2)
        print("after", v1)
        return max(tr('y2', v2), c['k'])


if __name__ == "__main__":
    import sys

    import copy
    import re

    def _shown(value):
        return re.sub(r"0x[0-9a-fA-F]+", "0xADDR", repr(value))

    def _calls(label, function, argument_sets):
        for arguments in argument_sets:
            arguments = copy.deepcopy(arguments)
            try:
                outcome = "-> " + _shown(function(*arguments))
            except Exception as error:
                outcome = f"raised {type(error).__name__}: {_shown(str(error))}"
            print(label, outcome, "| arguments after:", _shown(arguments))

    def _value(label, produce):
        try:
            print(label, "=", _shown(produce()))
        except Exception as error:
            print(label, "raised", type(error).__name__, _shown(str(error)))

    M = sys.modules[__name__]
    _calls('M.K().f1', M.K().f1, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K().f2', M.K().f2, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K().f3', M.K().f3, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _value('M.LOG[-50:]', lambda: M.LOG[-50:])
    _value('M.G', lambda: M.G)
    _value('public names of M', lambda: sorted(name for name in dir(M) if not name.startswith('_')))
