# Generated by tests.differential.grammar from seed 11254 (typed); refactored by towel --no-types, its behaviour changed.
# Rerun: python -m tests.differential.fuzz --count 1 --seed 11254 --modes default
# The audit's gram_t11254: annotated source, refactored with --no-types.
# Round-3 audit P1-7: the block reads a name before binding it; the call site passes it in, where it is not local.
from typing import Any

LOG: list[str] = []
G = 5


def tr(tag: str, v: Any) -> Any:
    print("tr", tag, repr(v))
    LOG.append(tag)
    return v


class Box:
    def __init__(self, v: int) -> None:
        self.v = v

    def __repr__(self) -> str:
        return f"Box({self.v!r})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Box) and self.v == other.v


class Ctx:
    def __init__(self, tag: str) -> None:
        self.tag = tag

    def __enter__(self) -> str:
        print("enter", self.tag)
        return self.tag

    def __exit__(self, et: Any, ev: Any, tb: Any) -> bool:
        print("exit", self.tag, et.__name__ if et else None)
        return False


def bump() -> int:
    global G
    G += 1
    return G


class K:
    def __init__(self) -> None:
        self.count = 0

    def f1(self, a: int, b: list[int], c: dict[str, int], o: Box) -> Any:
        print("p3", ((c.get('k', 0) if (4 > 0 and G < 5) else a) and (o.v if o.v == 8 else c.get('k', 0))), a)
        o.v = len(f"{len(b)}-{a}")
        b.append(o.v)
        if c.get('k', 0) != 0:
            raise ValueError("bad " + str((c['k'] and max(8, len(b)))))
        def v1(q):
            return q + c.get('k', 0)
        v2 = v1(v2)
        print("after", v2)
        return None

    def f2(self, x: int, y: list[int], z: dict[str, int], w: Box) -> Any:
        print("p3", ((z.get('k', 0) if (4 > 0 and G < 5) else x) and (w.v if w.v == 8 else z.get('k', 0))), x)
        w.v = len(y)
        y.append(w.v)
        if z.get('k', 0) != 0:
            raise ValueError("bad " + str((z['k'] and max(8, len(y)))))
        def v1(q):
            return q + z.get('k', 0)
        v2 = v1(v2)
        print("after", v2)
        return None


if __name__ == "__main__":
    import sys

    import copy
    import re

    def _shown(value):
        return re.sub(r"0x[0-9a-fA-F]+", "0xADDR", repr(value))

    def _calls(label, function, argument_sets):
        for arguments in argument_sets:
            arguments = copy.deepcopy(arguments)
            try:
                outcome = "-> " + _shown(function(*arguments))
            except Exception as error:
                outcome = f"raised {type(error).__name__}: {_shown(str(error))}"
            print(label, outcome, "| arguments after:", _shown(arguments))

    def _value(label, produce):
        try:
            print(label, "=", _shown(produce()))
        except Exception as error:
            print(label, "raised", type(error).__name__, _shown(str(error)))

    M = sys.modules[__name__]
    _calls('M.K().f1', M.K().f1, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.K().f2', M.K().f2, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _value('M.LOG[-50:]', lambda: M.LOG[-50:])
    _value('M.G', lambda: M.G)
    _value('public names of M', lambda: sorted(name for name in dir(M) if not name.startswith('_')))
