# Generated by the round-3 audit's grammar generator, in its first revision, as its gram_u0217;
# refactored by towel --no-types, its behaviour changed. Seed 217 of tests.differential.grammar
# now draws another case, so this fixture is its only record.
# Round-3 audit P1-7: the block reads a name before binding it; the call site passes it in, where it is not local.
# Since the P1-7 fix the pair is declined: the block reads v6 before binding it.
LOG = []
G = 5


def tr(tag, v):
    print("tr", tag, repr(v))
    LOG.append(tag)
    return v


class Box:
    def __init__(self, v):
        self.v = v

    def __repr__(self):
        return f"Box({self.v!r})"

    def __eq__(self, other):
        return isinstance(other, Box) and self.v == other.v


class Ctx:
    def __init__(self, tag):
        self.tag = tag

    def __enter__(self):
        print("enter", self.tag)
        return self.tag

    def __exit__(self, et, ev, tb):
        print("exit", self.tag, et.__name__ if et else None)
        return False


def bump():
    global G
    G += 1
    return G


def f1(a, b, c, o):
    print("prefix", G)
    match (sum(b) - (a % 7)):
        case 0:
            v1 = max((c.get('k', 0) + len(b)), (len(b) * len(b)))
        case 1 | 2:
            print("p7", (max(o.v, c.get('k', 0)) and o.v), abs((G if c.get('k', 0) > len(b) else o.v)))
        case _:
            LOG.append(str(max(G, max(c.get('k', 0), len(b)))))
    with Ctx("w3") as v2:
        v3 = (1 if len(f"{a}-{a}") < sum(q for q in b if q > a) <= G else 0)
    v4 = (tr('q6', G) if (a > 0 and c.get('k', 0) < 5) else len(f"{G}-{a}"))
    def v5(q):
        return q + v4
    v6 = v5((lambda q: q * 2 + 1)(len(f"{v6}-{a}")))
    print("after", v6)
    return None


def f2(a, b, c, o):
    print("prefix", G)
    match (sum(b) - (a % 7)):
        case 0:
            v1 = a
        case 1 | 2:
            print("p7", (max(o.v, c.get('k', 0)) and o.v), abs((G if c.get('k', 0) > len(b) else o.v)))
        case _:
            LOG.append(str(max(G, max(c.get('k', 0), len(b)))))
    with Ctx("w3") as v2:
        v3 = (1 if len(f"{a}-{a}") < sum(q for q in b if q > a) <= G else 0)
    v4 = (tr('q6', G) if (a > 0 and c.get('k', 0) < 5) else len(f"{G}-{a}"))
    def v5(q):
        return q + v4
    v6 = v5((lambda q: q * 2 + 1)(len(f"{v6}-{a}")))
    print("after", v6)
    return None


if __name__ == "__main__":
    import sys

    import copy
    import re

    def _shown(value):
        return re.sub(r"0x[0-9a-fA-F]+", "0xADDR", repr(value))

    def _calls(label, function, argument_sets):
        for arguments in argument_sets:
            arguments = copy.deepcopy(arguments)
            try:
                outcome = "-> " + _shown(function(*arguments))
            except Exception as error:
                outcome = f"raised {type(error).__name__}: {_shown(str(error))}"
            print(label, outcome, "| arguments after:", _shown(arguments))

    def _value(label, produce):
        try:
            print(label, "=", _shown(produce()))
        except Exception as error:
            print(label, "raised", type(error).__name__, _shown(str(error)))

    M = sys.modules[__name__]
    _calls('M.f1', M.f1, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _calls('M.f2', M.f2, [(0, [], {}, M.Box(0)), (1, [1, 2, 3], {'k': 1}, M.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, M.Box(-2)), (-2, [4], {'j': 7}, M.Box(3)), (2, [1, 1], {'k': 5}, M.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, M.Box(0))])
    _value('M.LOG[-50:]', lambda: M.LOG[-50:])
    _value('M.G', lambda: M.G)
    _value('public names of M', lambda: sorted(name for name in dir(M) if not name.startswith('_')))
