# Copyright 2025-2026 Eric Allen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tests.differential.grammar from seed 1209; refactored by towel --cross-module --no-types, its behaviour changed.
# Rerun: python -m tests.differential.fuzz --count 1 --seed 1209 --modes cross
# The audit's gram_u1209.
# Round-3 audit P1-1: a for target rebinding a name bound before the block; an empty loop leaves the helper's name unbound.
if __name__ == "__main__":
    import pkg.common as C
    import pkg.a as A
    import pkg.b as B
    import copy
    import re

    def _shown(value):
        return re.sub(r"0x[0-9a-fA-F]+", "0xADDR", repr(value))

    def _calls(label, function, argument_sets):
        for arguments in argument_sets:
            arguments = copy.deepcopy(arguments)
            try:
                outcome = "-> " + _shown(function(*arguments))
            except Exception as error:
                outcome = f"raised {type(error).__name__}: {_shown(str(error))}"
            print(label, outcome, "| arguments after:", _shown(arguments))

    def _value(label, produce):
        try:
            print(label, "=", _shown(produce()))
        except Exception as error:
            print(label, "raised", type(error).__name__, _shown(str(error)))

    _calls('A.f1', A.f1, [(0, [], {}, C.Box(0)), (1, [1, 2, 3], {'k': 1}, C.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, C.Box(-2)), (-2, [4], {'j': 7}, C.Box(3)), (2, [1, 1], {'k': 5}, C.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, C.Box(0))])
    _calls('B.f2', B.f2, [(0, [], {}, C.Box(0)), (1, [1, 2, 3], {'k': 1}, C.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, C.Box(-2)), (-2, [4], {'j': 7}, C.Box(3)), (2, [1, 1], {'k': 5}, C.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, C.Box(0))])
    _value('C.LOG[-50:]', lambda: C.LOG[-50:])
    _value('C.G', lambda: C.G)
    _value('(A.G, B.G)', lambda: (A.G, B.G))
    B.G = 100
    _calls('B.f2', B.f2, [(0, [], {}, C.Box(0)), (1, [1, 2, 3], {'k': 1}, C.Box(1)), (3, [0, 5, -1], {'k': 0, 'j': 2}, C.Box(-2)), (-2, [4], {'j': 7}, C.Box(3)), (2, [1, 1], {'k': 5}, C.Box(2)), (7, [9, 8, 7, 6], {'k': -3}, C.Box(0))])
    _value('public names of C', lambda: sorted(name for name in dir(C) if not name.startswith('_')))
    _value('public names of A', lambda: sorted(name for name in dir(A) if not name.startswith('_')))
    _value('public names of B', lambda: sorted(name for name in dir(B) if not name.startswith('_')))
